name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore StreamDeckTradfri/StreamDeckTradfri.sln
    - name: Build
      run: dotnet build StreamDeckTradfri/StreamDeckTradfri.sln --no-restore
    - name: Test
      run: dotnet test StreamDeckTradfri/StreamDeckTradfri.sln --no-build --verbosity normal
